"""Software Documentation Formatter Agent - Generates LaTeX/PDF/DOCX for software docs"""
import os
import subprocess
import tempfile
from datetime import date
from typing import Dict, Any, List
from backend.agents.base_agent import BaseAgent
from backend.config import settings
from backend.logger import logger


class SoftwareDocFormatterAgent(BaseAgent):
    """
    Assembles software documentation sections.
    Produces: .tex, .pdf (via pdflatex), and .docx (via Node.js docx package).
    Uses report document class with chapter-level sections.
    """

    def __init__(self):
        super().__init__("Software Doc Formatter Agent", settings.model_flash_lite)

    def process(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Format the software documentation.

        Args:
            input_data: {
                'sections': List[{name, content}],
                'selected_title': str,
                'repo_name': str,
                'repo_url': str,
                'job_dir': str,
            }

        Returns:
            {
                'tex_path': str,
                'pdf_path': str | None,
                'docx_path': str | None,
                'latex_errors': str,
            }
        """
        sections = input_data.get('sections', [])
        selected_title = input_data.get('selected_title', 'Software Documentation')
        repo_name = input_data.get('repo_name', 'Unknown')
        repo_url = input_data.get('repo_url', '')
        job_dir = input_data.get('job_dir', tempfile.gettempdir())

        logger.workflow_step("Software Doc Formatter", "Assembling document")

        # Generate LaTeX
        tex_content = self._generate_latex(sections, selected_title, repo_name, repo_url)
        tex_path = os.path.join(job_dir, 'software_doc.tex')
        with open(tex_path, 'w', encoding='utf-8') as f:
            f.write(tex_content)

        # Compile PDF
        pdf_path, latex_errors = self._compile_pdf(tex_path, job_dir)

        # Log errors
        errors_log = os.path.join(job_dir, 'formatter_latex_errors.log')
        with open(errors_log, 'w', encoding='utf-8') as f:
            f.write(latex_errors or 'No errors')

        # Generate DOCX
        docx_path = self._generate_docx(sections, selected_title, repo_name, job_dir)

        return {
            'tex_path': tex_path,
            'pdf_path': pdf_path,
            'docx_path': docx_path,
            'latex_errors': latex_errors,
        }

    def _latex_escape(self, text: str) -> str:
        """Escape special LaTeX characters."""
        # Use a placeholder so that { and } introduced by later replacements
        # are not themselves re-escaped.
        _BS = '\x00BS\x00'
        text = text.replace('\\', _BS)
        text = text.replace('{', r'\{')
        text = text.replace('}', r'\}')
        text = text.replace(_BS, r'\textbackslash{}')
        text = text.replace('&', r'\&')
        text = text.replace('%', r'\%')
        text = text.replace('$', r'\$')
        text = text.replace('#', r'\#')
        text = text.replace('_', r'\_')          # fixes "! Missing $ inserted."
        text = text.replace('^', r'\textasciicircum{}')
        text = text.replace('~', r'\textasciitilde{}')
        text = text.replace('<', r'\textless{}')
        text = text.replace('>', r'\textgreater{}')
        return text

    def _generate_latex(
        self,
        sections: List[Dict],
        title: str,
        repo_name: str,
        repo_url: str,
    ) -> str:
        """Generate a LaTeX document using the report class."""
        safe_title = self._latex_escape(title)
        author = repo_name.split('/')[0] if '/' in repo_name else repo_name

        body_parts = []
        for sec in sections:
            if sec['name'].lower() in ('title page', 'table of contents',
                                        'list of figures', 'list of abbreviations'):
                continue  # handled by LaTeX commands
            sec_title = self._latex_escape(sec['name'])
            sec_body = self._latex_escape(sec['content'])
            if sec['name'].lower().startswith('appendix'):
                body_parts.append(f'\\appendix\n\\chapter{{{sec_title}}}\n{sec_body}\n')
            else:
                body_parts.append(f'\\chapter{{{sec_title}}}\n{sec_body}\n')

        body = '\n'.join(body_parts)

        tex = f"""\\documentclass[12pt,a4paper]{{report}}
\\usepackage{{geometry}}
\\geometry{{margin=1in}}
\\usepackage{{hyperref}}
\\usepackage{{listings}}
\\usepackage{{booktabs}}
\\usepackage{{graphicx}}
\\usepackage{{amsmath}}
\\usepackage{{setspace}}
\\onehalfspacing

\\title{{{safe_title}}}
\\author{{{self._latex_escape(author)}}}
\\date{{\\today}}

\\begin{{document}}
\\maketitle
\\thispagestyle{{empty}}

\\newpage
\\section*{{Declaration}}
This document was automatically generated by Dr. Document from repository analysis.
The content is derived solely from the codebase and does not represent any official submission.

\\newpage
\\tableofcontents
\\listoffigures

\\newpage
{body}

\\end{{document}}
"""
        return tex

    def _compile_pdf(self, tex_path: str, job_dir: str) -> tuple:
        """Run pdflatex up to 3 times."""
        pdf_path = tex_path.replace('.tex', '.pdf')
        errors = ''
        max_retries = 3

        for attempt in range(1, max_retries + 1):
            try:
                result = subprocess.run(
                    ['pdflatex', '-interaction=nonstopmode', '-output-directory', job_dir,
                     tex_path],
                    capture_output=True,
                    text=True,
                    timeout=120,
                )
                errors = result.stdout + result.stderr
                if result.returncode == 0 and os.path.exists(pdf_path):
                    logger.success(f"Software doc PDF compiled on attempt {attempt}")
                    subprocess.run(
                        ['pdflatex', '-interaction=nonstopmode', '-output-directory', job_dir,
                         tex_path],
                        capture_output=True, text=True, timeout=120,
                    )
                    return pdf_path, ''
                else:
                    # Extract only error/warning lines to keep logs readable
                    relevant = '\n'.join(
                        line for line in errors.splitlines()
                        if line.startswith('!') or 'Error' in line or 'error' in line
                    )
                    logger.warning(
                        f"pdflatex attempt {attempt} failed (rc={result.returncode})"
                        + (f":\n{relevant}" if relevant else f"\n{errors[-800:]}")
                    )
            except FileNotFoundError:
                logger.warning(
                    "pdflatex binary not found — install the system package, not the pip wrapper.\n"
                    "    Ubuntu/Debian : sudo apt-get install texlive-latex-base\n"
                    "    macOS         : brew install basictex\n"
                    "    Windows       : install MiKTeX from https://miktex.org"
                )
                return None, (
                    'pdflatex binary not found. '
                    'Install the system package (e.g. texlive-latex-base) — '
                    "'pip install pdflatex' only provides a Python wrapper and does not supply the binary."
                )
            except subprocess.TimeoutExpired:
                errors = 'pdflatex timed out'
            except Exception as e:
                errors = str(e)

        return None, errors

    def _generate_docx(
        self,
        sections: List[Dict],
        title: str,
        repo_name: str,
        job_dir: str,
    ) -> str | None:
        """Generate DOCX using python-docx."""
        try:
            from docx import Document
            from docx.shared import Pt
            from docx.enum.text import WD_ALIGN_PARAGRAPH
        except ImportError:
            logger.warning("python-docx not installed — skipping DOCX generation")
            return None

        try:
            docx_path = os.path.join(job_dir, 'software_doc.docx')
            author = repo_name.split('/')[0] if '/' in repo_name else repo_name
            today = date.today().strftime('%B %d, %Y')
            skip_sections = {
                'title page', 'table of contents',
                'list of figures', 'list of abbreviations',
            }

            doc = Document()

            # Set default font
            style = doc.styles['Normal']
            style.font.name = 'Times New Roman'
            style.font.size = Pt(12)

            # Cover page
            title_para = doc.add_paragraph()
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = title_para.add_run(title)
            run.bold = True
            run.font.size = Pt(24)
            run.font.name = 'Times New Roman'

            subtitle_para = doc.add_paragraph()
            subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = subtitle_para.add_run(
                'Submitted in partial fulfillment of project documentation requirements'
            )
            run.italic = True
            run.font.size = Pt(12)
            run.font.name = 'Times New Roman'

            author_para = doc.add_paragraph()
            author_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = author_para.add_run(author)
            run.font.size = Pt(14)
            run.font.name = 'Times New Roman'

            date_para = doc.add_paragraph()
            date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = date_para.add_run(today)
            run.font.size = Pt(12)
            run.font.name = 'Times New Roman'

            gen_para = doc.add_paragraph()
            gen_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = gen_para.add_run('Generated by Dr. Document')
            run.italic = True
            run.font.size = Pt(10)
            run.font.name = 'Times New Roman'

            doc.add_page_break()

            # Sections
            for sec in sections:
                if sec['name'].lower() in skip_sections:
                    continue
                doc.add_heading(sec['name'], level=1)
                for paragraph in sec['content'].split('\n\n'):
                    cleaned = ' '.join(paragraph.split('\n')).strip()
                    if cleaned:
                        p = doc.add_paragraph()
                        run = p.add_run(cleaned)
                        run.font.name = 'Times New Roman'
                        run.font.size = Pt(12)

            doc.save(docx_path)
            logger.success("Software doc DOCX generated")
            return docx_path
        except Exception as e:
            logger.error(f"DOCX error: {e}")
            return None
